# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-10-06 11:33:16
"""
import arcpy

def AppendToSchema():  # AppendToSchema

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Regional_New_590 = "Regional-New-590"
    UpdateProjects_2_ = "UpdateProjects"

    # Process: Append (Append) 
    UpdateProjects = arcpy.Append_management(inputs=[Regional_New_590], target=UpdateProjects_2_, schema_type="NO_TEST", field_mapping="DivCode \"division\" true true false 255 Text 0 0,First,#,Regional-New-590,DIV,0,255;iProjID \"ProjectID\" true true false 4 Long 0 0,First,#,Regional-New-590,PROJECT_ID,-1,-1;sProjectName \"ProjectName\" true true false 255 Text 0 0,First,#,Regional-New-590,PROJECT_NAME,0,255", subtype="", expression="")[0]

    # Process: Calculate Field (Calculate Field) 
    UpdateProjects_4_ = arcpy.CalculateField_management(in_table=UpdateProjects, field="ProjYr", expression="2022", expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\VMGIS\VMGISPro\VMGISPro.gdb", workspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\VMGIS\VMGISPro\VMGISPro.gdb"):
        AppendToSchema()
