# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder and Christopher Grasteit on : 2021-12-10 11:00:05
"""
import arcpy
from sys import argv

def FullRevisedOffshoreRun(Input_Project_to_be_Processed="Now perhaps the final run still\\Project_Area_CentralCoast_Q2_Missing2", Add_Division_Name="\"Central Coast\"", Add_Year="2021"):  # FullRevisedOffshoreRun

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    VegProject_PolyEdit_3_ = "VegProject_PolyEdit"

    # Process: Add Fields (multiple) (Add Fields (multiple)) 
    Project_Area_Kern = arcpy.AddFields_management(in_table=Input_Project_to_be_Processed, field_description=[["DivCode", "TEXT", "", "255", "", ""], ["ProjectYear", "LONG", "", "", "2021", ""]])[0]

    # Process: Calculate Field (Calculate Field) 
    Project_Area_Kern_3_ = arcpy.CalculateField_management(in_table=Input_Project_to_be_Processed, field="DivCode", expression=Add_Division_Name, expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

    # Process: Calculate Field (2) (Calculate Field) 
    Project_Area_Kern_4_ = arcpy.CalculateField_management(in_table=Project_Area_Kern_3_, field="ProjectYear", expression=Add_Year, expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

    # Process: Append (Append) 
    VegProject_PolyEdit = arcpy.Append_management(inputs=[Project_Area_Kern_4_], target=VegProject_PolyEdit_3_, schema_type="NO_TEST", field_mapping="CIRCUITNAME \"Circuit Name\" true true false 50 Text 0 0,First,#,C:\\Users\\c5gr\\OneDrive - PGE\\Desktop\\Data\\OneVM\\StorageOfDivisions-Offshore\\InProcess\\Sanfranscisco_Q1.gdb\\Project_Area_Sanfranscisco_Q1,CIRCUITNAME,0,50;DivCode \"division\" true true false 255 Text 0 0,First,#,C:\\Users\\c5gr\\OneDrive - PGE\\Desktop\\Data\\OneVM\\StorageOfDivisions-Offshore\\InProcess\\Sanfranscisco_Q1.gdb\\Project_Area_Sanfranscisco_Q1,DivCode,0,255;iProjID \"ProjectID\" true true false 0 Long 0 0,First,#,Project_Area_Sanfranscisco_Q1,Project_ID,-1,-1;sProjectName \"ProjectName\" true true false 255 Text 0 0,First,#,Project_Area_Sanfranscisco_Q1,CIRCUITNAME,0,50;ProjYr \"ProjectYear\" true true false 0 Long 0 0,First,#,Project_Area_Sanfranscisco_Q1,ProjectYear,-1,-1", subtype="", expression="")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Foot_US',0.3048006096012192]]", scratchWorkspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\OneVM\OneVMProcess.gdb", workspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\OneVM\OneVMProcess.gdb"):
        FullRevisedOffshoreRun(*argv[1:])
