# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder and Christopher Grastetit on : 2021-12-10 10:59:53
"""
import arcpy
from sys import argv

def FullProcessLiDARGroupRevisedRun(Input_Layer_to_be_Processed="Gina Process\\Mission_project_area_polygon_edit", Division="\"Mission\""):  # FullProcessLiDARGroupRevisedRun

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Model Environment settings
    with arcpy.EnvManager(cellSize="MAXOF", outputCoordinateSystem="PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Foot_US',0.3048006096012192]]", scratchWorkspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\OneVM\OneVMProcess.gdb", 
                          workspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\OneVM\OneVMProcess.gdb"):
        VegProject_PolyEdit_2_ = "VegProject_PolyEdit"

        # Process: Calculate Field (2) (Calculate Field) 
        project_area_polygon_DeAnza_2_ = arcpy.CalculateField_management(in_table=Input_Layer_to_be_Processed, field="PGE_DIVISION", expression=Division, expression_type="PYTHON3", code_block="", field_type="TEXT")[0]

        # Process: Append (Append) 
        VegProject_PolyEdit = arcpy.Append_management(inputs=[project_area_polygon_DeAnza_2_], target=VegProject_PolyEdit_2_, schema_type="NO_TEST", field_mapping="CIRCUITNAME \"Circuit Name\" true true false 50 Text 0 0,First,#,Gina Process\\project_area_polygon_DeAnza,CIRCUIT_NAME,0,50;DivCode \"division\" true true false 255 Text 0 0,First,#,Gina Process\\project_area_polygon_DeAnza,PGE_DIVISION,0,255;iProjID \"ProjectID\" true true false 0 Long 0 0,First,#,Gina Process\\project_area_polygon_DeAnza,PROJECT_ID,-1,-1;sProjectName \"ProjectName\" true true false 255 Text 0 0,First,#,Gina Process\\project_area_polygon_DeAnza,PROJECT_NAME,0,255;ProjYr \"ProjectYear\" true true false 0 Long 0 0,First,#,Gina Process\\project_area_polygon_DeAnza,PROJECT_YEAR,-1,-1", subtype="", expression="")[0]

if __name__ == '__main__':
    FullProcessLiDARGroupRevisedRun(*argv[1:])
