# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-09-29 11:36:51
"""
import arcpy

def Model_Project_Area():  # Model_Project_Area

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS['NAD_1983_UTM_Zone_10N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',1640416.666666667],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-123.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Foot_US',0.3048006096012192]]"):
        PriOHConductor = "Overhead Lines\\PriOHConductor"
        PriOHConductor_2_ = "S:\\VM_Technology\\VM_GIS_DATA\\Resource_Data\\Electric_Distribution\\EDGIS_PRIOH_Extract_20210618.gdb\\PriOHConductor"
        project_area_polygon = "project_area_polygon"
        SkyLidarSpans05012021 = "Overhead Lines\\SkyLidarSpans05012021"
        PriOHConductor_3_ = "S:\\VM_Technology\\VM_GIS_DATA\\Resource_Data\\Electric_Distribution\\EDGIS_PRIOH_Extract_20210618.gdb\\PriOHConductor"
        SkyLidarSpans05012021_2_ = "Overhead Lines\\SkyLidarSpans05012021"
        project_area_polygon_2_ = "project_area_polygon"

        # Process: Buffer (Buffer) 
        PriOHConductor_Buffer_100m = "C:\\Users\\c5gr\\OneDrive - PGE\\Desktop\\Data\\VMGIS\\2021_Project_Area_California.gdb\\PriOHConductor_Buffer_100m"
        arcpy.Buffer_analysis(in_features=PriOHConductor, out_feature_class=PriOHConductor_Buffer_100m, buffer_distance_or_field="100 Meters", line_side="FULL", line_end_type="FLAT", dissolve_option="LIST", dissolve_field=["CIRCUITNAME"], method="PLANAR")

        # Process: Simplify Polygon (Simplify Polygon) 
        PriOHConductor_Simplify_800m = "C:\\Users\\c5gr\\OneDrive - PGE\\Desktop\\Data\\VMGIS\\2021_Project_Area_California.gdb\\PriOHConductor_Simplify_800m"
        with arcpy.EnvManager(transferGDBAttributeProperties=False):
            PriOHConductor_Simplify_800m_Pnt = arcpy.SimplifyPolygon_cartography(in_features=PriOHConductor_Buffer_100m, out_feature_class=PriOHConductor_Simplify_800m, algorithm="POINT_REMOVE", tolerance="800 Meters", minimum_area="0 SquareFeet", error_option="RESOLVE_ERRORS", collapsed_point_option="NO_KEEP", in_barriers=[PriOHConductor_2_, project_area_polygon, SkyLidarSpans05012021])[0]

        # Process: Smooth Polygon (Smooth Polygon) 
        PriOHConductor_Smooth_1000m = "C:\\Users\\c5gr\\OneDrive - PGE\\Desktop\\Data\\VMGIS\\2021_Project_Area_California.gdb\\PriOHConductor_Smooth_1000m"
        with arcpy.EnvManager(transferGDBAttributeProperties=False):
            arcpy.SmoothPolygon_cartography(in_features=PriOHConductor_Simplify_800m, out_feature_class=PriOHConductor_Smooth_1000m, algorithm="PAEK", tolerance="1000 Meters", endpoint_option="FIXED_ENDPOINT", error_option="RESOLVE_ERRORS", in_barriers=[PriOHConductor_3_, SkyLidarSpans05012021_2_, project_area_polygon_2_])

        # Process: Eliminate Polygon Part (Eliminate Polygon Part) 
        PriOHConductor_Eliminate_1000km2 = "C:\\Users\\c5gr\\OneDrive - PGE\\Desktop\\Data\\VMGIS\\2021_Project_Area_California.gdb\\PriOHConductor_Eliminate_1000km2"
        arcpy.EliminatePolygonPart_management(in_features=PriOHConductor_Smooth_1000m, out_feature_class=PriOHConductor_Eliminate_1000km2, condition="AREA", part_area="1000 SquareKilometers", part_area_percent=0, part_option="CONTAINED_ONLY")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\VMGIS\VMGISPro\VMGISPro.gdb", workspace=r"C:\Users\c5gr\OneDrive - PGE\Desktop\Data\VMGIS\VMGISPro\VMGISPro.gdb"):
        Model_Project_Area()
